site:
  title: OpenNMS Plugin for Grafana Documentation
  url: https://opennms-helm-doc.netlify.com
  start_page: helm::index.adoc
content:
  sources:
  - url: https://github.com/OpenNMS/opennms-helm.git
    branches: HEAD
    tags: v*
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
output:
  clean: true
  dir: ./public
  destinations
  - provider: fs
  - provider: archive
